apiVersion: v1
kind: Service
metadata:
  name: {{ include "netbird.server.fullname" . }}-stun
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "netbird.server.labels" . | nindent 4 }}
{{- with .Values.server.stunService.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  type: {{ .Values.server.stunService.type }}
  externalTrafficPolicy: Local

  ports:
    - name: stun
      port: {{ .Values.server.stunService.port }}
      targetPort: stun
      protocol: UDP
      {{- if and (eq .Values.server.stunService.type "NodePort") (not (kindIs "invalid" .Values.server.stunService.nodePort)) }}
      nodePort: {{ .Values.server.stunService.nodePort }}
      {{- end }}
  selector:
    {{- include "netbird.server.selectorLabels" . | nindent 4 }}

